### ISSUE TITLE
Identify and define the stakeholders for C API

### ISSUE THREAD

**Issue by iritkatriel** [capi-workgroup/problems#26]
Let's create a list of the CAPI stakeholders, with as much colour as we can add to clarify the use cases and their particular needs.

We can start with this list and iterate:

1. CPython core devs
2. Alternative implementation devs
3. Extension authors
4. code generator devs (Cython, pybind11, ...)
5. "packaging people"
6. final users
7. language bindings

**Comment by encukou** [comment]
I'd say pybind11 is a language binding rather than a code generator. Maybe these categories overlap enough and we can only list “language bindings”? After all Cython is also a language.

Where does HPy fit?

**Comment by encukou** [comment]
- Debuggers, profilers, JITs, accelerators (Numba, Austin, Cinder, PyCharm ...)

**Comment by iritkatriel** [comment]
To clarify - this issue is not just about creating a list but also compiling a full description of each use case/stakeholder. Anyone who can contribute a paragraph or two, please do. Once we have all the information I'll try to coalesce it into one coherent document.

**Comment by zooba** [comment]
* Embedders (e.g. Blender, OBS)

Hosting CPython inside another native application involves interacting not just with object APIs, but also the threading and execution model, signals, initialization, import system, and typically representing complex data models in a way Python can use without having to make deep copies.

**Comment by iritkatriel** [comment]
@zooba is there a clear distinction between the embedding and language binding use cases? Or do they overlap?

**Comment by encukou** [comment]
Something like this?
It might be better as a shared document.

- Language bindings  (pybind11, PyO3, PySide, Cython, ...)

Commonly, these need to create custom objects (e.g.  function/module objects, traceback entries) that match the behavior of some equivalent Python code as closely as possible.
They commonly need to dynamically create objects that are `static` in traditional C extensions (e.g. classes/modules), and need CPython to manage their state and lifetime.
They also need to adapt foreign objects (strings, GC'd containers) well as possible, and with low overhead..
They look for ways to adapt exotic mechanisms, execution models and guarantees to the Python way (green threads/continuations, one-writer-or-multiple-readers semantics, virtual multiple inheritance, 1-based indexing, super-long inheritance chains, ...).

- Alternative implementations (PyPy, GraalPython, Jython, ...)

These want to provide C-API that's similar to CPython.
They need abstract API that hides implementation details.

- Code generators (Cython, Argument Clinic, ...) and external API layers (HPy, pythoncapi-compat, ...)

These can *provide* alternative API, freeing CPython from having to cater to  a particular use case.
They need CPython to provide minimal building blocks (no “sugar” -- convenience API).
Some want to squeeze maximum preformance out of CPython.

**Comment by iritkatriel** [comment]
> * Code generators (Cython, Argument Clinic, ...) and external API layers (HPy, pythoncapi-compat, ...)
> 
> These can _provide_ alternative API, freeing CPython from having to cater to a particular use case. 

Maybe we could call them "alternative APIs" (as opposed to alternative implementations)?   Or "C-api abstractions"?

**Comment by encukou** [comment]
Sure!

And, embedders also need:
- configuring the interpreter (import paths, inittab, `sys.argv`, ...)
- frozen modules
- clean interpreter shutdown and restart
- running multiple independent interpreters (esp. when embedded in a library that wants to avoid global effects)

**Comment by encukou** [comment]
Yeah, I was thinking along the same lines. All I have is an unfinished draft (from before your post), but I have to call it a day so I'll share it:
> Maybe we need to untangle into these categories, with most projects needing more of them:
> - Foreign data models and runtimes: adapt other object/execution models to Python
> - Non-C languages: avoid C compiler quirks
> - Embedding: configure and control the interpreter (import path setup, frozen modules, clean shutdown & restart, managing multiple independent interpreters, ...)

How do these areas compare to this repo's  “themes”?

**Comment by zooba** [comment]
> I'm beginning to think that maybe instead of defining the list of stakeholders, and then listing what each of them needs, we could being by defining the list of _actions_ (or _things_ or _concerns_)

This is a good way to present it, though I think the way we're developing the list is fine. It's easier to look at actual users and see what they're doing, and then go back to figure out what they have in common with other users.

And yes, embedders _almost always_ do language bindings as well, otherwise the embedded Python may be very uninteresting. Though it's possible that you have another API (e.g. Minecraft fires-and-forgets a lot of text commands over _kind of_ a socket, rather than directly interacting with the game engine, largely due to the complexity in mapping the threading models together).

**Comment by vstinner** [comment]
> I put all of this on a wiki page, we can iterate on it there: https://github.com/capi-workgroup/problems/wiki/Requirements

I close this issue since https://peps.python.org/pep-0731/ has been written and the PEP describes Stakeholders.

If you would like more concrete actions, like having an explicit list of stakeholders, I suggest to open an issue in: https://github.com/capi-workgroup/api-evolution
