### ISSUE TITLE
Use of legacy C integer types

### ISSUE THREAD

**Issue by markshannon** [capi-workgroup/problems#27]
We use the C type `long` a lot in the C API, which is problem because `long` varies in size across platforms in a way that is hard to deal with. A `long` might be 32bit or 64bit on a 64bit platform, which makes for lots of `#ifdef`s and conditional logic that wouldn't be needed if we used C99 `stdint` integer types.

Our code is also full of `int` where we mean `int32_t`. `int` is almost always 32 bit, but it is not guaranteed.

**Comment by encukou** [comment]
Issue for proposed guidelines: https://github.com/capi-workgroup/api-evolution/issues/10

**Comment by vstinner** [comment]
> Issue for proposed guidelines: https://github.com/capi-workgroup/api-evolution/issues/10

I close this issue, let's continue the discussion there.
