### ISSUE TITLE
No clear separation between "fast API" (unsafe) and "safe API"

### ISSUE THREAD

**Issue by vstinner** [capi-workgroup/problems#61]
For historical reasons, the Python C API is a mixture of various kinds of functions:

* Internal functions, exposed simply because it was the only way to be able to use it in CPython itself
* Private functions, supposed to be not be used by 3rd party code, but sometimes added on purpose since we couldn't agree if it should be added or not
* Clean and safe public API which is designed to be stable accross Python versions

In Python 3.7, a new ``Include/internal/`` subdirectory was added: **internal API** which **must not** be used outside CPython have been moved slowly (one by one) there. Most of these functions are no longer exported: so technically it's no longer possible to use them outside Python. Moreover, the ``Py_BUILD_CORE`` macro must be defined to access it: it's an opt-in option (similar to issue #54 idea) to clearly point out that: hey, **you're in the danger zone**!

Recently, in Python 3.12, the concept of "Unstable API" was added: [PEP 689 – Unstable C API tier](https://peps.python.org/pep-0689/). This one is a middleground for function that we want to expose as "public", but are known to be unstable between Python versions, like PyCore_New() which became: **PyUnstable_**Code_New().

There is still a gray area between "fast API" and "safe API".

Examples of unsafe fast APIs vs safe APIs:

* ``PyTuple_GET_ITEM()`` vs ``PyTuple_GetItem()`` (runtime type check, check index bounds)
* ``_PyThreadState_UncheckedGet()`` (can return NULL) vs ``PyThreadState_Get()`` (fatal error instead of returning NULL)

Differences between "fast API" and "safe API":

* Fast API usually avoid runtime type check and avoid index bounds check, assertions may be used. Safe API implement runtime checks.
* Fast API can sometimes implemented as **macro** or **static inline function** (ex: access structure members). Safe API is usually implemente as opaque function call.

It's more common for the "fast API" to **rely on the compiler** to produce efficient code (ex: inline code). Sadly, it may cause more portability issues (compiler not fully implementing a C standard or a specific function).

**Comment by vstinner** [comment]
See issue #31 "The C API is weakly typed" which is related.

**Comment by vstinner** [comment]
One practical problem is the lack of a real "debug mode" to debug bugs or crashes in the unsafe fast API: see issue #36 "Debug mode that can be easily activated without recompilation" for example.

**Comment by vstinner** [comment]
Issue #31 asks also to raise TypeError rather than SystemError in functions like PyTuple_Size(), PyList_Append() or PyDict_GetItemWithError() if the first parameter has an unexpected type (these functions expect respectively: tuple, list, dict; or subtypes of these types).

That's another difference: **passing the wrong type to a fast API is treated as a bug** in the C extension by calling ``PyErr_BadInternalCall()`` which raises a **SystemError*.

Whereas generic safe API like PyObject_GetItem() raises **TypeError** if the argument is not a mapping (nor a sequence). That's not "a bug" but the "normal expected behavior". In Python, you get the same exception when using ``obj["key"]`` if *obj* is not a mapping (nor a sequence).

**Comment by pitrou** [comment]
Just a note: if you call it "fast API", everyone will instinctively try to use it. If you call it "intrusive API", people will be more cautious.

You could also call it "unsafe API", but it's only unsafe if you're using it wrong, of course.

> It's more common for the "fast API" to **rely on the compiler** to produce efficient code (ex: inline code). Sadly, it may cause more portability issues (compiler not fully implementing a C standard or a specific function).

Do we care about non-conforming compilers?

**Comment by vstinner** [comment]
About the **naming**, IMO **Unsafe** is more a better name than "Fast" or "Unchecked". For example, I don't think that _PyUnicode_**Fast**CopyCharacters() was a clever choice. The other existing name is "Unchecked": _PyThreadState_**Unchecked**Get().

"Unsafe" means that "it is unsafe *unless* you check assumptions in the caller". In many cases, it's easy to check these assumptions. For example, PyDict_GetItem() makes the assumption that you pass a dictionary. (Well, this one currently that the argument type is a dict.) It's common that function creates a dict or store a dict, and so know the argument type.

I prefer to mark unsafe functions as "Unsafe" (in their name) to help people discovering the API that: oh, maybe they should avoid these functions until they fully understand their usage.

The "PyUnstable" API seems to have a different purpose.

**Comment by vstinner** [comment]
> Do we care about non-conforming compilers?

I don't think that you should pretend that putting "Fast" in a function name makes it "faster" :-) I'm not convinced that removing a few pre-conditions and avoiding error handling in general has a significant performance difference. Maybe avoiding indirections by using PyDict_GetItem() instead of PyObject_GetItem() makes a larger difference. I don't know. People just have believes and nobody runs benchmarks :-)

**Comment by pitrou** [comment]
Well, if you're accessing all (or most) elements in a list, avoiding checks every time probably makes a difference. If you're doing a single access, then it probably doesn't matter.

**Comment by vstinner** [comment]
Follow-up issue: https://github.com/capi-workgroup/api-evolution/issues/45. I close this issue since there is no concrete action which can be triggered to enhance the situation. If I manage to design a more concrete action, I will open a new issue.
