### ISSUE TITLE
Things that I may work on to make doc more maintainer friendly during the sprint

### ISSUE THREAD

**Issue by willingc** [capi-workgroup/problems#76]
- [x] Split Introduction into History and Purposes of C-API
    - History (evolution over 30 years - brief summary)
    - Current purposes of the C-API
- [x] Add a reference section at end of document
    - Irit's talk (sprint)
    - Petr's talk (sprint)
    - HPy Learnings talk (sprint)
    - Victor's talk (sprint)
    - Europython talk from PySide maintainer (link in discord)
- [ ] Add a section on terminology (stable, internal, etc.)

**Comment by encukou** [comment]
For reference, here's a report on the issues PySide had 5 years ago when switching to the stable ABI: https://github.com/pyside/pyside2-setup/blob/5.11/sources/shiboken2/libshiboken/pep384impl_doc.rst

**Comment by vstinner** [comment]
The sprint is over, can we close this issue @willingc?
